### ISSUE TITLE
What style guidance for package names

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/translation_guide#1]
https://github.com/rosadmin/ropensci-review-tools/issues/16#issuecomment-1238213692

Cc @yabellini

**Comment by maelle** [comment]
https://github.com/r-lib/downlit/issues/158

**Comment by maelle** [comment]
Ideally I'd like to recommend `{package}` because

- code tags are easily ignored by DeepL API;
- we get more links to pkgdown docs.

**Comment by yabellini** [comment]
Great suggestions.  I think you can merge your PR and close this one.  I will start to populate the content.  (I can't close this issues :-P )
