### ISSUE TITLE
How to add the glossary

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/translation_guide#2]
@yabellini should the glossary live here or should the book read it from https://github.com/ropensci-review-tools/glossary?

**Comment by yabellini** [comment]
Probably we want to read it from https://github.com/ropensci-review-tools/glossary because we are updating, and we want to update in a single place.

**Comment by maelle** [comment]
Ok! Do you need help from me adding it and if so in which chapter? Happy to do it.

**Comment by yabellini** [comment]
Yes please, and I think we have a chapter that is call Glossary, we can add there, and then we can reference to that chapter in any place we need it.
