### ISSUE TITLE
Translate the Preface to Spanish

### ISSUE THREAD

**Issue by yabellini** [ropensci-review-tools/translation_guide#22]

**Comment by yabellini** [comment]
@maelle can you please create the PR with the translation to Spanish of index.Rmd?

**Comment by maelle** [comment]
but index.Rmd already exists with English content, do you want me to

- first overwrite it with the Spanish text
- then translate it?

**Comment by yabellini** [comment]
> but index.Rmd already exists with English content, do you want me to
> 
>     * first overwrite it with the Spanish text
> 
>     * then translate it?

Yes, both have content, but index.Rmd is the file with the complete content. The Spanish file is the one that is not update and have old and incomplete text.  So we need to take the English text and translate to Spanish. 
* first overwrite index.Rmd with the English content.
* then translate it to Spanish. 

So we have the Spanish version of the guidelines for the comm call on Thursday. :-) Thank you so much!
