### ISSUE TITLE
Translation from English to Spanish of motivation.Rmd

### ISSUE THREAD

**Issue by yabellini** [ropensci-review-tools/translation_guide#35]
@maelle can you please create the PR with the translation?

**Comment by maelle** [comment]
motivation.es.Rmd already exists, do you want me to

- first overwrite it with the English content
- then translate it?

**Comment by yabellini** [comment]
> motivation.es.Rmd already exists, do you want me to
> 
>     * first overwrite it with the English content
> 
>     * then translate it?

Yes, please!
