### ISSUE TITLE
Review - Chp 2 - General Guidelines

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-review-tools/translation_guide#54]
I'll be dropping my comments regarding my review (PR #52 ) as issues for each chapter. This is a check list so you can keep track of which comments are resolved. As always, feel free to ignore anything that doesn't suite (just check it off as 'resolved' in that case).

- [x] **Would this chapter be better title "Overview"?** It's not really a set of guidelines, more of an overview of the process
    - [x] The only thing that looks like guidelines are the list of general things to do during review (the 4 items after "In each step of this process, we ask you to:"). I'd suggest moving this list to Chp 3 under a new subsection called "General Guidelines" at the start of the "Technical aspects" (leave the paragraphs before and after).
- [x] Does the "Translation is typically the most time-consuming" statement really need a reference? 
- [x] Don't forget that the babeldown package also has a workflow for *updating* translations (I added this text to the bullets under Technical infrastructure etc.
- [ ] I mentioned that "We created the babeldown package...", although technically, this was Maëlle's work, perhaps that should read "Maëlle created the ..." to give proper attribution?
- [x] Under "try to be gender-neutral", should there be a comment regarding the new gender neutral pronouns some languages have been adopting more recently? Or is that implied (or part of the language-specific guidelines)?
- [x] "Edition" is almost never used as a verb, so I would suggest avoiding it as one in this guide. Consider "Overall Review" or "Editing" as alternatives. I've changed it in my edits.
    - [x] But this means that I would suggest changing the word "Edition" in the concept map figure to "Overall Review" 
- [x] The text occasionally refers to "Language Agreements", but that term isn't really used in Chapter 4. I'd suggest being consistent by calling them "Specific Language Guidelines", and then when you add the section on how to add a new language, spend more space there talking about how these guidelines come about through community discussion and agreements. 
- [x] I made quite a few changes to the citations section for consistency and also to better match APA (e.g., no first names for authors, just initials). I also made some opinionated changes to how to cite translation work on a CV, see what you think!
- [x] Footnotes can refer to the same reference. This way if anything changes you only need to update it once, although having only one reference does put the note farther away from it's use in the text on multiple uses. See what you think about how I've reorganized them.

**Comment by yabellini** [comment]
> Does the "Translation is typically the most time-consuming" statement really need a reference?

I included it because it is something that people tend to ask, and it is better to provide a citation.

**Comment by yabellini** [comment]
> I mentioned that "We created the babeldown package...", although technically, this was Maëlle's work, perhaps that should read "Maëlle created the ..." to give proper attribution? 

I interpret the we as "rOpenSci," and I agree this is Maëlle's work. It is ok for me to change it.  @maelle, what do you think?

**Comment by steffilazerte** [comment]
Oh it's not wrong as it is (I agree 'we' is rOpenSci), I was just thinking that @maelle was the main driver of the project :grin:

**Comment by yabellini** [comment]
> Under "try to be gender-neutral", should there be a comment regarding the new gender neutral pronouns some languages have been adopting more recently? Or is that implied (or part of the language-specific guidelines)?

This is for the specifics of each language.  This makes me think I will change the general rule a little bit and move the details to Spanish.
